# Generated by Django 2.2.10 on 2020-05-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_configurations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfconfiguration',
            name='node_type',
            field=models.CharField(choices=[('VALIDATOR', 'VALIDATOR')], default='VALIDATOR', max_length=9),
        ),
    ]
