# Generated by Django 3.0.6 on 2020-07-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_configurations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfconfiguration',
            name='node_type',
            field=models.CharField(choices=[('CONFIRMATION_VALIDATOR', 'CONFIRMATION_VALIDATOR'), ('PRIMARY_VALIDATOR', 'PRIMARY_VALIDATOR')], max_length=22),
        ),
    ]
