# Generated by Django 3.1.3 on 2020-11-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_configurations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfconfiguration',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AddIndex(
            model_name='selfconfiguration',
            index=models.Index(fields=['ip_address', 'port', 'protocol'], name='self_config_ip_addr_0b8467_idx'),
        ),
        migrations.AddConstraint(
            model_name='selfconfiguration',
            constraint=models.UniqueConstraint(fields=('ip_address', 'port', 'protocol'), name='self_configurations_selfconfiguration_unique_ip_port_proto'),
        ),
    ]
