# Generated by Django 2.2.10 on 2020-05-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_configurations', '0002_auto_20200516_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfconfiguration',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
