from thenewboston.constants.network import CONFIRMATION_VALIDATOR, PRIMARY_VALIDATOR

NODE_TYPE_CHOICES = [
    (CONFIRMATION_VALIDATOR, CONFIRMATION_VALIDATOR),
    (PRIMARY_VALIDATOR, PRIMARY_VALIDATOR),
]
