# Generated by Django 3.0.6 on 2020-07-05 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validator',
            name='registration_fee',
        ),
    ]
