# Generated by Django 3.1 on 2020-08-30 02:11

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=64, unique=True)),
                ('balance', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(281474976710656)])),
                ('balance_lock', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'default_related_name': 'accounts',
            },
        ),
    ]
