# Generated by Django 3.0.6 on 2020-07-05 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('node_identifier', models.CharField(max_length=64, unique=True)),
                ('port', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(65535)])),
                ('protocol', models.CharField(choices=[('http', 'http'), ('https', 'https')], max_length=5)),
            ],
            options={
                'default_related_name': 'connection_requests',
            },
        ),
        migrations.AddConstraint(
            model_name='connectionrequest',
            constraint=models.UniqueConstraint(fields=('ip_address', 'port'), name='unique_ip_address_port'),
        ),
    ]
